// Bookmarks
export const CREATE_BOOKMARKED_COURSE = 'CREATE_BOOKMARKED_COURSE';
export const LIST_BOOKMARKED_COURSES = 'LIST_BOOKMARKED_COURSES';
export const GOT_BOOKMARKED_COURSE = 'GOT_BOOKMARKED_COURSE';
export const REMOVED_BOOKMARK = 'REMOVED_BOOKMARK';