// Course
export const CREATE_COURSE = 'CREATE_COURSE';
export const LIST_COURSES = 'LIST_COURSES';
export const SELECTED_COURSE = 'SELECTED_COURSE';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const ARCHIVE_COURSE = 'ARCHIVE_COURSE';